--- 
Acura:
  - CL
  - Integra
  - Legend
  - MDX
  - NSX
  - RDX
  - RL
  - RSX
  - SLX
  - TL
  - TSX
  - Vigor
Alfa Romeo:
  - "164"
  - Graduate
  - GTV-6
  - Milano
  - Quadrifoglio
  - Spider
Am General:
  - Hummer
Aston Martin:
  - DB7
  - DB7 Vantage
  - DB9
  - Lagonda
  - V12 Vanguish
  - V8 Vantage
  - Vantage
  - Virage
  - Zagato
Audi:
  - "100"
  - "200"
  - "4000"
  - "5000"
  - "80"
  - "90"
  - A3
  - A4
  - A5
  - A6
  - A8
  - allroad
  - Cabroliet
  - GT
  - Q7
  - Quattro
  - R8
  - RS 4
  - RS6
  - S4
  - S5
  - S6
  - S8
  - TT
  - TTS
BMW:
  - "128"
  - "135"
  - "318"
  - "320"
  - "323"
  - "325"
  - "328"
  - "330"
  - "335"
  - "524"
  - "525"
  - "528"
  - "530"
  - "533"
  - "535"
  - "540"
  - "545"
  - "550"
  - "633"
  - "635"
  - "645"
  - "650"
  - "733"
  - "735"
  - "740"
  - "745"
  - "750"
  - "760"
  - "840"
  - "850"
  - Alpina B7
  - L6
  - L7
  - M
  - M3
  - M5
  - M6
  - X3
  - X5
  - X6
  - Z3
  - Z4
  - Z4 M
  - Z8
Bentley:
  - Arnage
  - Azure
  - Brooklands
  - Continental
  - Continental Flying Spur
  - Continental GT
  - Continental GTC
  - Eight
  - Mulsanne
  - Mulsanne S
  - Mulsanne Turbo
  - Turbo R
  - Turbo RL
  - Turbo RT
  - Turbo S
Buick:
  - Century
  - Electra
  - Enclave
  - Estate Wagon
  - LaCrosse
  - LeSabre
  - Lucerne
  - Park Avenue
  - Rainier
  - Reatta
  - Regal
  - Rendevous
  - Riviera
  - Roadmaster
  - Skyhawk
  - Skylark
  - Somerset
  - Terraza
Cadillac:
  - Allante
  - Brougham
  - Catera
  - Cimarron
  - CTS
  - DeVille
  - DTS
  - Eldorado
  - Escalade
  - Escalade ESV
  - Escalade EXT
  - Escalade Hybrid
  - Fleetwood
  - Seville
  - Sixty Special
  - SRX
  - STS
  - XLR
Chevrolet:
  - 1500 (pre 2000)
  - 2500 (pre 2000)
  - 3500 (pre 2000)
  - Astro
  - Avalanche
  - Aveo
  - Baretta
  - Blazer
  - C10/K10
  - C20/K20
  - C30/K30
  - Camaro
  - Caprice
  - Caprice Classic
  - Cavalier
  - Celebrity
  - Chevette
  - Citation
  - Classic
  - Cobalt
  - Colorado
  - Corsica
  - Corvette
  - El Camino
  - Equinox
  - Express 1500
  - Express 2500
  - Express 3500
  - HHR
  - Impala
  - Lumina
  - Lumina APV
  - Luv
  - Malibu
  - Malibu Classic
  - Malibu Maxx
  - Metro
  - Mone Carlo
  - Nova
  - Pickup (Other)
  - Prizm
  - S-10
  - S-10 Blazer
  - Silverado 1500
  - Silverado 1500 Hybrid
  - Silverado 2500
  - Silverado 3500
  - Spectrum
  - Sprint
  - SSR
  - Suburban
  - Tahoe
  - Tracker
  - TrailBlazer
  - TrailBlazer EXT
  - Traverse
  - Uplander
  - V20
  - V30
  - Van
  - Venture
Chrysler:
  - "300"
  - 300C
  - 300M
  - Aspen
  - Aspen Hybrid
  - Cirrus
  - Concorde
  - Conquest
  - Cordoba
  - Crossfire
  - E Class
  - Executive
  - Fifth Avenue
  - Grand Voyager
  - Imperial
  - Laser
  - LeBaron
  - LHS
  - New Yorker
  - Pacifica
  - Prowler
  - PT Cruiser
  - Seabring
  - TC (Maserati)Town & Country
  - Voyager
Daewoo:
  - Lanos
  - Leganza
  - Nubira
Daihatsu:
  - Charade
  - Rocky
Delorean:
  - DMC-12
Dodge:
  - "400"
  - "600"
  - Aries
  - Aspen Hybrid
  - Avenger
  - Caliber
  - Caravan
  - Challenger
  - Charger
  - Colt
  - Conquest
  - D100
  - D150
  - D250
  - D350
  - Dakota
  - Daytona
  - Diplomat
  - Durango
  - Durango Hybrid
  - Dynasty
  - Grand Caravan
  - Intrepid
  - Journey
  - Lancer
  - Magnum
  - Mini Ram
  - Mirada
  - Monaco
  - Neon
  - Nitro
  - Omni
  - Pickup (Other)
  - Raider
  - Ram 1500
  - Ram 2500
  - Ram 3500
  - Ram 50
  - Ram Van
  - Ram Wagon
  - Ramcharger
  - Rampage
  - Shadow
  - Spirit
  - Sprinter
  - Stealth
  - Stratus
  - Van
  - Viper
  - W100
  - W150
  - W250
  - W350
Eagle:
  - Medallion
  - Premier
  - Summit
  - Talon
  - Vision
Ferrari:
  - "308"
  - "328"
  - "348"
  - 360 Modena
  - "456"
  - 456 GT
  - 512 M
  - 512 TR
  - "550"
  - 550 Barchetta
  - 575 M
  - 599 GTB Fiorano
  - 612 Scaglietti
  - Challenge Stradale
  - Enzo
  - F355
  - F40
  - F430
  - F50
  - GTB
  - GTO
  - Mondial
  - Mondial t
  - Superamerica
  - Testarossa
Fiat:
  - Pininfarina
  - Spider 2000
  - X1/9
Ford:
  - Aerostar
  - Aspire
  - Bronco
  - Bronco II
  - Club Wagon
  - Contour
  - Crown Victoria
  - E100
  - E150
  - E250
  - E350
  - E350 Super Duty
  - Edge
  - Escape
  - Escape Hybrid
  - Escort
  - Excursion
  - EXP
  - Expedition
  - Expedition EL
  - Explorer
  - Explorer Sport
  - Explorer Sport Trac
  - F100
  - F150
  - F250
  - F350
  - F450
  - Fairmont
  - Festiva
  - Five Hundred
  - Flex
  - Focus
  - Freestar
  - Freestyle
  - Fusion
  - Fusion Hybrid
  - GT
  - LTD
  - Mustang
  - Pickup (Other)
  - Probe
  - Ranger
  - Roadster
  - Taurus
  - Taurus X
  - Tempo
  - Thunderbird
  - Van
  - Windstar
  - ZX2
GMC:
  - 1500 (pre 1992)
  - 2500 (pre 1992)
  - 3500 (pre 1992)
  - Acadia
  - Caballero
  - Canyon
  - Envoy
  - Envoy XL
  - Envoy XUV
  - Jimmy
  - Pickup
  - Rally
  - S-15 Jimmy
  - S-15 Pickup
  - Safari
  - Savana 1500
  - Savana 2500
  - Savana 3500
  - Sonoma
  - Suburban
  - Vandura
  - Yukon
  - Yukon Hybrid
  - Yukon XL
Geo:
  - Metro
  - Prizm
  - Spectrum
  - Storm
  - Tracker
Honda:
  - Accord
  - Accord Hybrid
  - Civic
  - Civic Hybrid
  - CRX
  - CR-V
  - del Sol
  - Element
  - Fit
  - Insight
  - Odyssey
  - Passport
  - Pilot
  - Prelude
  - Ridgeline
  - S2000
Hummer:
  - H1
  - H1 Alpha
  - H2
  - H3
  - H3T
Hyundai:
  - Accent
  - Azera
  - Elantra
  - Elantra Touring
  - Entourage
  - Excel
  - Genesis
  - Santa Fe
  - Scoupe
  - Sonata
  - Tuburon
  - Tuscon
  - Veracruz
  - XG300
  - XG350
Infiniti:
  - EX35
  - FX35
  - FX45
  - FX50
  - G20
  - G35
  - G37
  - I30
  - I35
  - J30
  - M30
  - M35
  - M45
  - Q45
  - QX4
  - QX56
Isuzu:
  - Amigo
  - Ascender
  - Axiom
  - Hombre
  - i-280
  - i-290
  - i-350
  - i-370
  - I-Mark
  - Impulse
  - Oasis
  - Pickup
  - Rodeo
  - Rodeo Sport
  - Stylus
  - Trooper
  - VehiCROSS
Jaguar:
  - S-Type
  - Super V8
  - Super V8 Portfolio
  - Vanden Plas
  - X-Type
  - XF
  - XJ
  - XJ12
  - XJ6
  - XJ8
  - XJ12
  - XJ6
  - XJR
  - XJR-S
  - XJS
  - XK
  - XK8
  - XKR
Jeep:
  - Cherokee
  - CJ
  - CJ-7
  - Comanche
  - Commander
  - Compass
  - Grand Cherokee
  - Grand Wagoneer
  - J10 Truck
  - J20 Truck
  - Liberty
  - Patriot
  - Scrambler
  - Wagoneer
  - Wrangler
  - Wrangler Unlimiter
Kia:
  - Amanti
  - Borrego
  - Optima
  - Rio
  - Rio5
  - Rondo
  - Sedona
  - Sephia
  - Sorento
  - Soul
  - Spectra
  - Spectra5
  - Sportage
Lamborghini:
  - Countach
  - Diablo
  - Gallardo
  - Jalpa
  - Murcielago
Land Rover:
  - Defender
  - Discovery
  - Freelander
  - LR2
  - LR3
  - Range Rover
  - Range Rover Sport
Lexus:
  - ES 250
  - ES 300
  - ES 330
  - ES 350
  - GS 300
  - GS 350
  - GS 400
  - GS 430
  - GS 450h
  - GS 460
  - GX 470
  - IS 250
  - IS 300
  - IS 350
  - IS-F
  - LS 400
  - LS 430
  - LS 460
  - LS 600h L
  - LX 450
  - LX 470
  - LX 570
  - RX 300
  - RX 330
  - RX 350
  - RX 400h
  - SC 300
  - SC 400
  - SC 430
Lincoln:
  - Aviator
  - Blackwood
  - Continental
  - LS
  - Mark LT
  - Mark VII
  - Mark VIII
  - MKS
  - MKT
  - MKX
  - MKZ
  - Navigator
  - Town Car
  - Zephyr
Lotus:
  - Elise
  - Esprit
  - Esprit V8
  - Exige
  - Exige 5
Maserati:
  - "228"
  - 3200 GT
  - "430"
  - Biturbo
  - Coupe
  - GranSport
  - GranSport Spyder
  - GranTurismo
  - Quattroporte
  - Spyder
Maybach:
  - Landaulet
  - Type 57
  - Type 62
Mazda:
  - "323"
  - "626"
  - "929"
  - B2000
  - B2200
  - B2300
  - B2500
  - B2600
  - B3000
  - B4000
  - CX-7
  - CX-9
  - GLC
  - Mazda3
  - Mazda5
  - Mazda6
  - MazdaSpeed Miata MX-5
  - MazdaSpeed Protege
  - MazdaSpeed3
  - MazdaSpeed6
  - Miata MX-5
  - Millenia
  - MPV
  - MX-3
  - MX-6
  - Navajo
  - Pickup
  - Protege
  - Protege5
  - RX-7
  - RX-8
  - Tribute
  - Tribute Hybrid
Mercedes-Benz:
  - "190"
  - 240D
  - C-Class
  - CL-Class
  - CLK-Class
  - CLS-Class
  - E-Class
  - G-Class
  - GL-Class
  - GLK-Class
  - M-Class
  - R-Class
  - S-Class
  - SL-Class
  - SLK-Class
  - SLR McLaren
Mercury:
  - Brougham
  - Capri
  - Cougar
  - Grand Marquis
  - LN7
  - Lynx
  - Marauder
  - Mariner
  - Mariner Hybrid
  - Marquis
  - Milan
  - Milan Hybrid
  - Montego
  - Monterey
  - Mountainerr
  - Mystique
  - Sable
  - Topaz
  - Tracer
  - Villager
  - Zephyr
Mini:
  - Cooper
  - Cooper Clubman
  - Cooper S
  - Cooper S Clubman
Mitsubishi:
  - 3000GT
  - Cordia
  - Diamante
  - Eclipse
  - Endeavor
  - Expo
  - Galant
  - Lancer
  - Lancer Evolution
  - Lancer Sportback
  - Minivan
  - Mirage
  - Montero
  - Montero Sport
  - Outlander
  - Pickup
  - Precis
  - Raider
  - Sigma
  - Starion
  - Tredia
Morgan:
  - Aero 8
  - Plus 8
Nissan:
  - 200SX
  - 240SX
  - 280ZX
  - 300ZX
  - 350Z
  - 370Z
  - Altima
  - Altima Hybrid
  - Armada
  - Axxess
  - Frontier
  - GT-R
  - Maxima
  - Murano
  - NX
  - Pathfinder
  - Pickup
  - Pulsar
  - Quest
  - Rogue
  - Sentra
  - Stanza
  - Titan
  - Van
  - Versa
  - Xterra
Oldsmobile:
  - Achieva
  - Alero
  - Aurora
  - Bravada
  - Calais
  - Custom Cruiser
  - Cutlass
  - Cutlass Calais
  - Cutlass Ciera
  - Cutlass Cruiser
  - Cutlass Salon
  - Cutlass Supreme
  - Delta 88
  - Eighty-Eight
  - Firenza
  - Intrigue
  - LSS
  - Ninety-Eight
  - Omega
  - Regency
  - Silhouette
  - Toronado
Panoz:
  - AIV Roadster
  - Esperante
  - Roadster
Peugeot:
  - "405"
  - "504"
  - "505"
  - "604"
  - Liberte
Plymouth:
  - Acclaim
  - Breeze
  - Caravelle
  - Colt
  - Conquest
  - Gran Fury
  - Grand Voyager
  - Horizon
  - Laser
  - Neon
  - Prowler
  - Reliant
  - Sapporo
  - Scamp
  - Sundance
  - Turismo
  - Voyager
Pontiac:
  - "1000"
  - "2000"
  - "6000"
  - Aztek
  - Bonneville
  - Fiero
  - Firebird
  - G3
  - G5
  - G6
  - G8
  - Grand Am
  - Grand Prix
  - GTO
  - LeMans
  - Montana
  - Montana SV6
  - Parisienne
  - Phoenix
  - Safari
  - Solstice
  - Sunbird
  - Sunfire
  - Torrent
  - Trans Sport
  - Vibe
Porche:
  - "911"
  - "924"
  - "924"
  - "944"
  - "968"
  - Boxter
  - Carrera GT
  - Cayenne
  - Cayman
Rolls-Royce:
  - Camargue
  - Cornish
  - Park Ward
  - Phantom
  - Phantom Drophead Coupe
  - Phantom IV
  - Silver Cloud I
  - Silver Cloud II
  - Silver Seraph
  - Silver Spirit
  - Silver Spur
Saab:
  - 9-2X
  - 9-3
  - 9-5
  - 9-7X
  - "900"
  - "9000"
Saleen:
  - S7
Saturn:
  - Astra
  - Aura
  - Aura Green Line
  - Aura Hybrid
  - Ion
  - L
  - LS
  - LW
  - Outlook
  - Relay
  - SC
  - Sky
  - SL
  - SW
  - Vue
  - Vue Green Line
  - Vue Hybrid
Scion:
  - tC
  - xA
  - xB
  - xD
Smart:
  - ForTwo
Sterling:
  - "825"
  - "827"
Subaru:
  - B9 Tribeca
  - Baja
  - Brat
  - DL
  - Forester
  - GL
  - GL-10
  - Impreza
  - Justy
  - Legacy
  - Loyale
  - Outback
  - RX
  - STD
  - SVX
  - Tribeca
  - XT
Suzuki:
  - Aerio
  - Equator
  - Esteem
  - Forenza
  - Grand Vitara
  - Reno
  - Samura
  - Sidekick
  - Swift
  - SX4
  - Verona
  - Vitara
  - X-90
  - XL7
Toyota:
  - 4Runner
  - Avalon
  - Camry
  - Camry Hybrid
  - Camry Solara
  - Celica
  - Corolla
  - Cressida
  - ECHO
  - FJ Cruiser
  - Highlander
  - Highlander Hybrid
  - Land Cruiser
  - Matrix
  - MR2
  - Paseo
  - Pickup (Other)
  - Previa
  - RAV4
  - Sequoia
  - Sienna
  - Starlet
  - Supra
  - T100
  - Tacoma
  - Tercel
  - Tundra
  - Van
  - Venza
  - Yaris
Volkswagen:
  - Beetle
  - Cabrio
  - Cabriolet
  - CC
  - Corrado
  - Eos
  - Eurovan
  - Fox
  - Golf
  - GTI
  - Jetta
  - New Cabrio
  - Passat
  - Phaeton
  - Quantum
  - R32
  - Rabbit
  - Routan
  - Scirocco
  - Tiguan
  - Touareg
  - Touareg 2
  - Van
  - Vanagon
Volvo:
  - "240"
  - "740"
  - "760"
  - 760GT
  - "780"
  - "850"
  - "940"
  - "960"
  - C30
  - C70
  - Coupe
  - DL
  - GL
  - GLT
  - S40
  - S60
  - S70
  - S80
  - S90
  - V40
  - V50
  - V70
  - V90
  - XC70
  - XC90
Yugo:
  - Cabrio
  - GV
